on:
  # push to master trigger creating release version
  push:
    branches:
      - master
name: "Build and release"
jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.3'
      - run: flutter pub get
      - run: flutter create -t app ./
      - run: cd lib
      - run: ls -al
      - run: |
          flutter build apk --release --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }}"
          cd build/app/outputs/flutter-apk
          mv app-release.apk gq_1.0.${{ github.run_number }}.apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/gq_1.0.${{ github.run_number }}.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
