name: "Pull Request"
on:
  # push to master trigger creating release version
  pull_request:
jobs:
  runs-on: ubuntu-latest
  build:
    name: Build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.3'
      - run: flutter pub get
      - run: flutter create -t app ./
      - run: cd lib
      - run: ls -al
      - run: |
          flutter build apk --release
  tests:
    name: Tests
    needs: build
    steps:
      - run: |
          cd build/app/outputs/flutter-apk
          ls -al
# Line added for test perpuses