name: "Pull Request"
on:
  # push to master trigger creating release version
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.3'
      - run: flutter pub get
      - run: flutter create -t app ./
      - run: cd lib
      - run: ls -al
# ToDo Lines for build  apk:
#      - run: |
#          flutter build apk --release
#      - uses: actions/upload-artifact@master
#        with:
#          name: app-release
#          path: build/app/outputs/flutter-apk/app-release.apk
#  tests:
#    name: Tests
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - uses: actions/download-artifact@master
#        with:
#          name: app-release
#      - run: ls -al
# Line added for test perpuses